create extension if not exists pgcrypto;

create table if not exists public.xiangqi_puzzles (
  id text primary key,
  title text not null,
  fen text not null,
  moves jsonb not null default '[]'::jsonb,
  language text not null default 'en' check (language in ('en', 'zh')),
  theme text not null default 'wood' check (theme in ('wood', 'paper')),
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.video_jobs (
  id text primary key,
  puzzle_id text references public.xiangqi_puzzles(id) on delete set null,
  title text not null,
  language text not null default 'en' check (language in ('en', 'zh')),
  status text not null default 'queued' check (status in ('queued', 'processing', 'ready_for_render', 'completed', 'failed')),
  input_payload jsonb not null default '{}'::jsonb,
  output_payload jsonb not null default '{}'::jsonb,
  output_url text,
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists xiangqi_puzzles_active_created_idx
  on public.xiangqi_puzzles (is_active, created_at desc);

create index if not exists video_jobs_status_created_idx
  on public.video_jobs (status, created_at desc);

create table if not exists public.content_candidates (
  id text primary key,
  fingerprint text not null unique,
  content_type text not null,
  title text not null,
  language text not null default 'en' check (language in ('en', 'zh')),
  source_kind text not null default 'generated',
  source_url text,
  status text not null default 'discovered' check (status in ('discovered', 'processing', 'published', 'failed')),
  priority_score numeric not null default 0,
  payload jsonb not null default '{}'::jsonb,
  published_job_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_provider_calls (
  id bigint generated by default as identity primary key,
  provider text not null,
  model text not null,
  slot_id text not null,
  project text not null default 'default',
  operation text not null,
  status text not null,
  error_class text,
  error_message text,
  status_code integer,
  usage jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_provider_state (
  provider text not null,
  model text not null,
  slot_id text not null,
  project text not null default 'default',
  consecutive_failures integer not null default 0,
  total_calls integer not null default 0,
  total_successes integer not null default 0,
  cooldown_until timestamptz,
  last_error text,
  updated_at timestamptz not null default now(),
  primary key (provider, model, slot_id)
);

create table if not exists public.automation_runs (
  id text primary key,
  trigger_name text not null,
  status text not null default 'running',
  started_at timestamptz not null,
  finished_at timestamptz,
  metrics jsonb not null default '{}'::jsonb,
  error_message text
);

create index if not exists content_candidates_status_score_idx
  on public.content_candidates (status, priority_score desc, created_at asc);
create index if not exists ai_provider_calls_created_idx
  on public.ai_provider_calls (created_at desc);

create or replace function public.touch_video_jobs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists video_jobs_updated_at on public.video_jobs;
create trigger video_jobs_updated_at
before update on public.video_jobs
for each row execute function public.touch_video_jobs_updated_at();

alter table public.xiangqi_puzzles enable row level security;
alter table public.video_jobs enable row level security;
alter table public.content_candidates enable row level security;
alter table public.ai_provider_calls enable row level security;
alter table public.ai_provider_state enable row level security;
alter table public.automation_runs enable row level security;

insert into storage.buckets (id, name, public)
values ('xiangqi-videos', 'xiangqi-videos', true)
on conflict (id) do update set public = excluded.public;

-- لا توجد سياسات عامة للقراءة أو الكتابة؛ مفتاح service_role يتجاوز RLS في الخادم فقط.
-- يمنع هذا أي عميل عام من إنشاء طلبات أو قراءة بيانات الإنتاج مباشرة.

insert into public.xiangqi_puzzles (id, title, fen, moves, language, theme, metadata)
values (
  'demo-left-wing',
  'The Quiet Trap on the Left Wing',
  'rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR r',
  '["0,6-0,5", "0,3-0,4", "1,7-1,4"]'::jsonb,
  'en',
  'wood',
  '{"source":"optional-supabase-seed"}'::jsonb
)
on conflict (id) do nothing;
